services:
  - type: web
    name: luxevoyage-api
    runtime: python
    plan: free
    rootDir: SRC
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: EMAIL_REMETENTE
        sync: false
      - key: EMAIL_DESTINATARIO
        sync: false
      # EMAIL_SENHA só é necessária se você NÃO for usar OAuth
      # (ou seja, se não subir credentials.json/token.json como Secret Files).
      - key: EMAIL_SENHA
        sync: false
